### ISSUE TITLE
Problem arising when removing the uploaded profile image in the sign up page

### ISSUE THREAD

**Issue by SBerenji** [SBerenji/COMP72070_Section03_Group07#14]
When the user uploads an image on the sign-up page and then removes it, they can still see the uploaded photo after signing in and being directed to the home page. This invokes a bad user experience and can be considered an important bug in the program.

**Comment by Sudhan-Dahake** [comment]
This bug has now been fixed. Now whenever the user clicks on Remove image the  event associated with it clears the array that is used to store that particular image.

Please refer to "Client Integration" Branch to see up to date Client development!
