### ISSUE TITLE
SQLiteDatabase closeDatabase function does not change the state of the database after called

### ISSUE THREAD

**Issue by serb2341** [SBerenji/COMP72070_Section03_Group07#19]
Hello, 

When performing unit testing on the SQLiteDatabase I am experiencing an error with the closeDatabase function. After calling this function, the isOpen function still registers the database as open. I think in the closeDatabase function, the db should be set to a nullptr again. 

I would be happy to answer any questions if this is unclear. This unit test can be found in FinalTCPServer_/unitTests_Sierra branch and it is titled "TestMethod42_SQLiteDatabase_closeDatabase"

Thank you.

**Comment by Sudhan-Dahake** [comment]
Thank you for bringing this to my notice sierra! I'll look into it.
