### ISSUE TITLE
Error when creating a post with no image

### ISSUE THREAD

**Issue by SBerenji** [SBerenji/COMP72070_Section03_Group07#27]
Based on TEST-SYS-32, the application almost breaks when the user tries to create a post without including an image. Based on REQ-USA-140 (included in the Detailed Requirement document) the user shall receive a pop-up message letting them know that they cannot post unless they fill out all the fields and include an image. However, this test fails since no message box appears on the screen.

**Comment by Sudhan-Dahake** [comment]
This issue has now been fixed. Uploading an Image of the post during "Create Post" process is now mandatory.
