### ISSUE TITLE
NewPost & HomeScreen Responsiveness Issue

### ISSUE THREAD

**Issue by serb2341** [SBerenji/COMP72070_Section03_Group07#3]
I am having trouble getting the NewPost and HomeScreen windows to be responsive.

**Comment by Sudhan-Dahake** [comment]
This issue is now fixed. I created a new "NewPost" window called "CreatePost" and also new "HomeScreen" Windows. Here, i changed multiple elements according to their functionalities. Moreover, i wrapped elements in a ViewBox, thereby making them responsive to resizing.
